language: python
python:
  - "2.7"
install:
  - pip install pelican
  - pip install markdown
before_script:
    - COMMIT_MESSAGE="Publishing site on `date "+%Y-%m-%d %H:%M:%S"` from `git log -n 1 --format='commit %h - %s'`"
script:
  - pelican content
  - git checkout -b master # Replace master with gh-pages if applicable
  - git add -f output/ # Replace _site/ with the build's output directory
  - 'git commit -m "${COMMIT_MESSAGE}"'
  - git filter-branch -f --subdirectory-filter output/ # Again, replace _site/
  # Obviously, replace with your repo's SSH URL and the appropriate branch
  - git push -f git@github.com:Bftech/bftech.github.io.git master:master
